[package]
name = "sabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={version="4.4.2", features=["derive"]}
anyhow = "1.0.75"
indicatif="0.17.6"
log="0.4.20"
env_logger="0.10.0"